[package]
name = "mdcolor"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.7"
serde_json = "1.0.64"
anyhow = "1.0.40"
clap = "2.33.3"
